---
version: '3.7'

volumes:
  api-db-data:
  pgadmin-data:

services:
  apidb:
    image: postgres:12.2-alpine
    ports:
      - "54334:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - api-db-data:/var/lib/postgresql

  api:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      FALCO_API_DATABASE_URL: postgres://test:test@apidb/test
    depends_on:
      - apidb

networks:
  default:
    name: backend-local
